#ifndef NETCHESSZX_SPECTRUM_UI_LAYOUT_H
#define NETCHESSZX_SPECTRUM_UI_LAYOUT_H

#include <stdint.h>

/* screen.asm mirrors the zone coordinates below. */

#define NETCHESSZX_TOP_TIMER_ROW 2u
#define NETCHESSZX_TOP_TIMER_SCAN 2u
#define NETCHESSZX_TOP_TIMER_COL 41u
#define NETCHESSZX_TOP_TURN_ROW 3u
#define NETCHESSZX_TOP_TURN_SCAN 2u
#define NETCHESSZX_TOP_TURN_CLEAR_COL 51u
#define NETCHESSZX_STATUS_CLOCK_COL 55u
#define NETCHESSZX_STATUS_TEXT_COL 1u
#define NETCHESSZX_STATUS_SCAN 2u

#define NETCHESSZX_GAME_BOARD_TOP_ROW 5u
#define NETCHESSZX_GAME_BOARD_LEFT_COL 1u

#define NETCHESSZX_INFO_PANEL_COL 18u
#define NETCHESSZX_INFO_TEXT_COL ((NETCHESSZX_INFO_PANEL_COL * 2u) + 1u)
#define NETCHESSZX_INFO_HEADER_ROW NETCHESSZX_GAME_BOARD_TOP_ROW
#define NETCHESSZX_INFO_HEADER_HLINE_ROW 6u
#define NETCHESSZX_INFO_CONTENT_FIRST_ROW 7u
#define NETCHESSZX_INFO_PANEL_CLEAR_FIRST_ROW NETCHESSZX_INFO_HEADER_ROW
#define NETCHESSZX_INFO_NOTICE_ROW 21u
#define NETCHESSZX_INFO_PANEL_CLEAR_LIMIT_ROW NETCHESSZX_INFO_NOTICE_ROW

#define NETCHESSZX_STATUS_ROW 22u
#define NETCHESSZX_INPUT_ROW 23u


#define NETCHESSZX_STATUS_LEFT_TEXT_SIZE 53u
#define NETCHESSZX_NOTICE_TEXT_SIZE 29u
#define NETCHESSZX_GAME_TIMER_TEXT_SIZE 23u

#define NETCHESSZX_MOVE_ROWS 7u
#define NETCHESSZX_MOVE_WHITE_TEXT_SIZE 14u
#define NETCHESSZX_MOVE_BLACK_OFFSET 18u
#define NETCHESSZX_MOVE_BLACK_TEXT_SIZE 13u
#define NETCHESSZX_MOVE_SLOT_SIZE 32u
#define NETCHESSZX_MOVE_BLACK_COL (NETCHESSZX_INFO_TEXT_COL + 14u)

#define NETCHESSZX_CHAT_ROWS 9u
#define NETCHESSZX_CHAT_MESSAGE_TEXT_MAX 42u
#define NETCHESSZX_CHAT_TEXT_SIZE 27u
#define NETCHESSZX_CHAT_SLOT_SIZE (NETCHESSZX_CHAT_TEXT_SIZE + 1u)
/* Bit 7 marks presentation-only control events and is never rendered. */
#define NETCHESSZX_CHAT_EVENT_SIDE_FLAG 0x80u
#define NETCHESSZX_CHAT_TEXT_OFFSET 7u
#define NETCHESSZX_CHAT_TEXT_LIMIT 25u
#define NETCHESSZX_CHAT_ICON_BYTE_COL NETCHESSZX_INFO_PANEL_COL
#define NETCHESSZX_CHAT_TIME_COL (NETCHESSZX_INFO_TEXT_COL + 2u)
#define NETCHESSZX_CHAT_TEXT_COL (NETCHESSZX_INFO_TEXT_COL + 8u)

#define NETCHESSZX_INFO_SETUP_LINE_BASE_ROW NETCHESSZX_INFO_CONTENT_FIRST_ROW
#define NETCHESSZX_INFO_MOVES_FIRST_ROW 6u
#define NETCHESSZX_INFO_MOVES_FIRST_Y 51u
#define NETCHESSZX_INFO_TIGHT_LINE_STEP 6u
#define NETCHESSZX_INFO_CHAT_TITLE_ROW 12u
#define NETCHESSZX_INFO_CHAT_HLINE_ROW 13u
#define NETCHESSZX_INFO_CHAT_FIRST_ROW 16u
#define NETCHESSZX_INFO_CHAT_FIRST_Y 110u
#define NETCHESSZX_PREFLIGHT_ROW_TIME_PREFIX "\013"




#endif
