#!/usr/bin/env python3
"""Pack Shatranj overlays as a variable-length atlas."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import struct
import tempfile
from pathlib import Path

MAGIC = b"NZOA"
VERSION = 1
HEADER_LEN = 100  # Fixed table plus padding that improves the packed NEX
FINGERPRINT_LEN = 4
FINGERPRINT_OFFSET = HEADER_LEN - FINGERPRINT_LEN
_OVERLAY_BLOCK_SIZE = os.environ.get("OVERLAY_BLOCK_SIZE", "2048").strip()
if _OVERLAY_BLOCK_SIZE not in {"2048", "4096", "8192"}:
    raise SystemExit("OVERLAY_BLOCK_SIZE must be 2048, 4096 or 8192")
BLOCK_SIZE = int(_OVERLAY_BLOCK_SIZE)
ORDER = [
    "RULES",
    "BOARD",
    "GUI_LOG",
    "MQTT_CONNECT",
    "MQTT_TX",
    "DIRECT",
    "MENU_CONFIG",
    "MENU_LOGIC",
    "SETUP",
    "INPUT_EDIT",
    "SAVELOAD",
    "RESTORE",
    "ABOUT",
    "FILEUI",
    "CONTROL",
    "CONFIG",
    "TIME_CONFIG",
]

SOURCE_SUFFIXES = {".asm", ".c", ".h", ".inc", ".json", ".py"}


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
        os.replace(temp_name, path)
    except BaseException:
        Path(temp_name).unlink(missing_ok=True)
        raise


def replace_if_changed(path: Path, data: bytes) -> bool:
    if path.exists() and path.read_bytes() == data:
        return False
    atomic_write(path, data)
    return True


def binding_digest(paths: list[Path], values: list[str]) -> bytes:
    digest = hashlib.sha256()

    for index, root in enumerate(paths):
        if root.is_file():
            files = [(Path(root.name), root)]
        elif root.is_dir():
            files = [
                (candidate.relative_to(root), candidate)
                for candidate in root.rglob("*")
                if candidate.is_file()
                and candidate.suffix.lower() in SOURCE_SUFFIXES
                and not candidate.name.endswith(".c.asm")
            ]
        else:
            raise SystemExit(f"atlas binding path not found: {root}")
        for relative, candidate in sorted(files, key=lambda item: item[0].as_posix()):
            data = candidate.read_bytes()
            digest.update(struct.pack("<H", index))
            digest.update(relative.as_posix().encode("utf-8"))
            digest.update(b"\0")
            digest.update(struct.pack("<I", len(data)))
            digest.update(data)

    for value in values:
        digest.update(b"V\0")
        digest.update(value.encode("utf-8"))
        digest.update(b"\0")
    return digest.digest()


def atlas_fingerprint(entries: list[tuple[int, int]], binding: bytes = b"") -> int:
    digest = hashlib.sha256()

    digest.update(MAGIC)
    digest.update(bytes((VERSION, len(entries))))
    digest.update(struct.pack("<H", HEADER_LEN))
    for offset, size in entries:
        digest.update(struct.pack("<HH", offset, size))
    digest.update(binding)
    return int.from_bytes(digest.digest()[:FINGERPRINT_LEN], "little")


def build_header(entries: list[tuple[int, int]], binding: bytes = b"") -> bytes:
    if FINGERPRINT_OFFSET < 8 + 4 * len(entries):
        raise SystemExit("atlas header too small")

    header = bytearray()
    header += MAGIC
    header += bytes((VERSION, len(entries)))
    header += struct.pack("<H", HEADER_LEN)
    for offset, size in entries:
        header += struct.pack("<HH", offset, size)
    header += bytes(HEADER_LEN - len(header))
    header[FINGERPRINT_OFFSET:HEADER_LEN] = atlas_fingerprint(
        entries, binding
    ).to_bytes(FINGERPRINT_LEN, "little")
    return bytes(header)


def write_table(
    path: Path, entries: list[tuple[int, int]], binding: bytes = b""
) -> bool:
    boundaries = [offset for offset, _size in entries]
    if entries:
        boundaries.append(entries[-1][0] + entries[-1][1])
    fingerprint = atlas_fingerprint(entries, binding).to_bytes(
        FINGERPRINT_LEN, "little"
    )
    lines = [
        "; Generated by tools/gen_overlay_atlas.py",
        f"ovl_atlas_count EQU {len(entries)}",
        *[
            f"ovl_atlas_fingerprint_{index} EQU {value}"
            for index, value in enumerate(fingerprint)
        ],
        "ovl_atlas_table:",
    ]
    lines += [f"    DW {boundary}" for boundary in boundaries]
    text = "\n".join(lines) + "\n"
    return replace_if_changed(path, text.encode("ascii"))


def write_paged_table(
    path: Path, sizes: list[int], binding: bytes = b""
) -> bool:
    entries = list(enumerate(sizes))
    fingerprint = atlas_fingerprint(entries, binding).to_bytes(
        FINGERPRINT_LEN, "little"
    )
    lines = [
        "; Generated by tools/gen_overlay_atlas.py (Next paged layout)",
        f"ovl_atlas_count EQU {len(sizes)}",
        *[
            f"ovl_atlas_fingerprint_{index} EQU {value}"
            for index, value in enumerate(fingerprint)
        ],
        "ovl_atlas_table:",
        *[f"    DW {size}" for size in sizes],
    ]
    return replace_if_changed(path, ("\n".join(lines) + "\n").encode("ascii"))


def seed_entries(
    path: Path, profile: str, order: list[str], size_limit: int
) -> list[tuple[int, int]]:
    document = json.loads(path.read_text(encoding="utf-8"))
    try:
        sizes = document[profile]
    except (KeyError, TypeError) as exc:
        raise SystemExit(f"atlas seed profile not found: {profile}") from exc
    if not isinstance(sizes, dict):
        raise SystemExit(f"atlas seed profile is not an object: {profile}")

    unexpected = set(sizes) - set(order)
    missing = set(order) - set(sizes)
    if unexpected or missing:
        raise SystemExit(
            f"invalid atlas seed {profile}: missing={sorted(missing)}, "
            f"unexpected={sorted(unexpected)}"
        )

    offset = HEADER_LEN
    entries = []
    for name in order:
        size = sizes[name]
        if isinstance(size, bool) or not isinstance(size, int) or not 0 <= size <= size_limit:
            raise SystemExit(f"invalid atlas seed size for {profile}/{name}: {size!r}")
        entries.append((offset, size))
        offset += size
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--asm-out", type=Path)
    parser.add_argument("--changed-stamp", type=Path)
    parser.add_argument("--sizes-out", type=Path)
    parser.add_argument("--bootstrap-asm", action="store_true")
    parser.add_argument("--seed-json", type=Path)
    parser.add_argument("--seed-profile")
    parser.add_argument("--extra", action="append", default=[])
    parser.add_argument("--binding-path", action="append", type=Path, default=[])
    parser.add_argument("--binding-value", action="append", default=[])
    parser.add_argument("--block-size", type=int, default=BLOCK_SIZE)
    parser.add_argument("--size-limit", type=int)
    args = parser.parse_args()
    if args.block_size not in (2048, 4096, 8192):
        raise SystemExit("block size must be 2048, 4096 or 8192")
    size_limit = args.block_size if args.size_limit is None else args.size_limit
    if size_limit <= 0 or size_limit > args.block_size:
        raise SystemExit("size limit must be positive and no larger than block size")

    if len(args.extra) != len(set(args.extra)):
        raise SystemExit("duplicate atlas extra")
    if set(args.extra) & set(ORDER):
        raise SystemExit("atlas extra duplicates a base overlay")
    if any(not name or not name.replace("_", "").isalnum() for name in args.extra):
        raise SystemExit("atlas extra names must be alphanumeric/underscore")
    order = ORDER + args.extra
    binding = binding_digest(args.binding_path, args.binding_value)

    if args.bootstrap_asm:
        if args.asm_out is None:
            raise SystemExit("--bootstrap-asm requires --asm-out")
        if args.seed_json is not None:
            if not args.seed_profile:
                raise SystemExit("--seed-json requires --seed-profile")
            entries = seed_entries(args.seed_json, args.seed_profile, order, size_limit)
        else:
            entries = [
                (HEADER_LEN + i * size_limit, size_limit)
                for i in range(len(order))
            ]
        if args.block_size == 8192:
            write_paged_table(args.asm_out, [size for _offset, size in entries], binding)
        else:
            write_table(args.asm_out, entries, binding)
        return 0

    entries: list[tuple[str, bytes]] = []
    for name in order:
        path = args.build_dir / f"{args.name}_{name}.OVL"
        data = path.read_bytes()
        if len(data) > size_limit:
            raise SystemExit(
                f"{path} too large: {len(data)} bytes (max {size_limit})"
            )
        entries.append((name, data))

    offset = HEADER_LEN
    payload = bytearray()
    sizes: dict[str, int] = {}
    asm_entries: list[tuple[int, int]] = []
    for name, data in entries:
        payload += data
        sizes[name] = len(data)
        asm_entries.append((offset, len(data)))
        offset += len(data)

    if args.block_size == 8192:
        paged = bytearray(len(entries) * args.block_size)
        for index, (_name, data) in enumerate(entries):
            start = index * args.block_size
            paged[start : start + len(data)] = data
        atomic_write(args.out, bytes(paged))
    else:
        header = build_header(asm_entries, binding)
        atomic_write(args.out, header + bytes(payload))
    if args.asm_out is not None:
        if args.block_size == 8192:
            changed = write_paged_table(
                args.asm_out, [len(data) for _name, data in entries], binding
            )
        else:
            changed = write_table(args.asm_out, asm_entries, binding)
        if args.changed_stamp is not None:
            replace_if_changed(
                args.changed_stamp, b"1\n" if changed else b"0\n"
            )
    sizes["HINTS"] = 0
    sizes["STATUS"] = 0
    sizes["total"] = args.out.stat().st_size
    sizes_json = (json.dumps(sizes, separators=(",", ":")) + "\n").encode("ascii")
    if args.sizes_out is not None:
        replace_if_changed(args.sizes_out, sizes_json)
    else:
        print(sizes_json.decode("ascii"), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
